[project]
name = "akira"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.1.0",
    "pandas>=2.3.3",
    "xlwings>=0.33.16",
    "pywin32>=306",
    "openpyxl>=3.1.0",
    "pathlib>=1.0.1",
]
